# Generated by Django 5.2.4 on 2025-08-20 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
