# Generated by Django 5.2.4 on 2025-08-20 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0002_rental_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='house_management.unit'),
        ),
    ]
