# Generated by Django 5.2.4 on 2025-08-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email'),
        ('house_management', '0003_alter_rental_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_owner', to='accounts.profile'),
        ),
    ]
