# Generated by Django 5.2.4 on 2025-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0005_alter_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
